### ISSUE TITLE
Create a landing page which explains all the features

### ISSUE THREAD

**Issue by anku255** [MLH-Fellowship/0.4.1-Execute.ly-frontend#1]
Hi! 

I think we should create a good landing page for our web app which lists out all the features with proper screenshots. For example  - 

- [ ] Executing code from programming books or assignments
- [ ] Executing code from image snippets
- [ ] Executing handwritten code
- [ ] Automatic language detection

and more...

I would love to hear what you guys think.

**Comment by sauravhiremath** [comment]
@anku255 These sound great!  Could you lemme know the UI framework decided? So I can hop in to contribute too

**Comment by anku255** [comment]
@sauravhiremath I am using Ant Design as the UI framework but for the landing page. I don't think you will be needing a lot of Ant Design components. 

The project also uses `styled-components` which should allow you to write plain css as well.

The basic layout for landing page should be like this - 

- Product Title
- Product Description
- A few example screenshots
- A button to take the user to upload page

I will provide the screenshots. and feel free to expand on the idea.

**Comment by YashKumarVerma** [comment]
Looks good to me !
