### ISSUE TITLE
Shows unable to compile 

### ISSUE THREAD

**Issue by YashKumarVerma** [MLH-Fellowship/0.4.1-Execute.ly-frontend#12]
https://github.com/MLH-Fellowship/0.4.1-Execute.ly-frontend/blob/dd5ec0204fb51ec40dc72c2f2600abe21f1c26a1/src/index.js#L4

The reason being the actual file name does not have capital A

**Comment by sauravhiremath** [comment]
That is an issue occuring when the project is run/compiled on different platforms (MacOS, Linux and Windows) in our case xD.

So, manual renaming of file 'app.js' to 'App.js' in the project dir should work without git triggering any change in the file.
