### ISSUE TITLE
Consider removing unused constant

### ISSUE THREAD

**Issue by YashKumarVerma** [MLH-Fellowship/0.4.1-Execute.ly-frontend#13]
https://github.com/MLH-Fellowship/0.4.1-Execute.ly-frontend/blob/dd5ec0204fb51ec40dc72c2f2600abe21f1c26a1/src/utils/constants.js#L3

Since now the plan for the python model has dropped, I think we can remove this

**Comment by anku255** [comment]
We are using actually planning to this for automatic language detection as per our latest discussion.
